version: '3.8'

services:
  db:
    image: postgres:15
    container_name: translation-chatbot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - chatbot-network

  redis:
    image: redis:7
    container_name: translation-chatbot-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - chatbot-network
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  postgres_data:
  redis_data:

networks:
  chatbot-network:
    driver: bridge
